[tool.poetry]
name = "artiq"
version = "7.7780"
description = "Advanced Real-Time Infrastructure for Quantum physics"
authors = ["M-Labs"]
license = "GPL v3"

[[tool.poetry.source]]
name = "oxionics"
url = "http://server-linux-0:3141/oiuser/oxionics/+simple/"
default = true

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "^1.21.4"
scipy = "^1.7.3"
python-dateutil = "^2.8.2"
prettytable = "^2.4.0"
h5py = "^3.6.0"
qasync = "^0.22.0"
pyqtgraph = "^0.12.3"
pygit2 = "^1.7.1"
pythonparser = "^1.3"
python-levenshtein = "^0.12.2"
pyqt5 = "5.12"
migen = "^0.9.2"
misoc = "^0.12"
jsonschema = "^4.2.1"
sipyco = "^1.2"

[tool.poetry.dev-dependencies]

[tool.cibuildwheel.linux]
before-all = "./add-llvm.sh"
manylinux-x86_64-image = "manylinux_2_24"
build= [
    "cp37-manylinux_x86_64", "cp38-manylinux_x86_64",
    "cp39-manylinux_x86_64", "cp310-manylinux_x86_64"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
