[workspace]
members = ["bootloader", "runtime", "ksupport", "satman"]

[profile.dev]
incremental = false # incompatible with LTO
lto = true
debug = 2

[patch.crates-io]
smoltcp = { git = "https://github.com/OxIonics/smoltcp", branch = "v0.8.x" }
