name: Package

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build_and_upload_wheel:
    uses: OxIonics/common-workflows/.github/workflows/package.yml@master
    secrets:
      PYPI_SERVER: ${{ secrets.PYPI_SERVER }}
      PYPI_LOGIN: ${{ secrets.PYPI_LOGIN }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    with:
      EXTRA_POETRY_INJECT_ARGS: >- 
        "path_version~=0.1" 
        --pip-args="--extra-index-url http://pypi.oxionics.com:3141/oiuser/oxionics/+simple/ --trusted-host pypi.oxionics.com"
      CHECK_PACKAGE_VERSION: false
