name: Package

on: workflow_dispatch

jobs:
  build_and_upload_wheel:
    name: Build and upload wheel
    container: python
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install poetry
        run: python -m pip install poetry

      - name: Build wheel
        run: poetry build

      - name: Configure poetry
        run: |
          poetry config repositories.oxionics \
            ${{ secrets.PYPI_SERVER }}/oiuser/oxionics/+simple
          poetry config http-basic.oxionics \
            ${{ secrets.PYPI_LOGIN }} ${{ secrets.PYPI_PASSWORD }}

      - name: Upload wheel
        run: poetry publish -r oxionics
