name: Package

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    container: ghcr.io/oxionics/poetry:1.3
    name: Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: poetry install

      - name: Test
        run: poetry run pytest -v artiq/test
